### ISSUE TITLE
Cannot use theme

### ISSUE THREAD

**Issue by hustshawn** [mkdocs/mkdocs-bootswatch#38] opened 2018-01-10 09:46 UTC
Hi,

I got the below error when applying your theme.

```
➜  demo-doc mkdocs serve
INFO    -  Building documentation... 
WARNING -  The theme 'flatly' does not appear to have a configuration file. Please upgrade to a current version of the theme. 
INFO    -  Cleaning site directory 
ERROR   -  Error building page index.md
```
It looks like a compatible issue with `mkdocs` version. Any clues on how to fix this?

```
➜  demo-doc python --version
Python 3.6.1

➜  demo-doc pip freeze | grep -i mkdocs
mkdocs==0.17.2
mkdocs-bootstrap==0.1.1
mkdocs-bootswatch==0.4.0
mkdocs-windmill==0.1.2
```

**Comment by isaccavalcante** [comment] 2018-01-18 21:34
I got it working installing the latest version directly from github:

````pip install git+https://github.com/mkdocs/mkdocs-bootswatch.git````

**Comment by isaccavalcante** [comment] 2018-01-18 21:35
I got it working by installing the latest version directly from github:
```sh
pip install git+https://github.com/mkdocs/mkdocs-bootswatch.git
```

**Comment by marcelstoer** [comment] 2018-01-20 00:34
Won't work for me when run on Travis (with MkDocs 0.17.2):

```
Collecting git+https://github.com/mkdocs/mkdocs-bootswatch.git
  Cloning https://github.com/mkdocs/mkdocs-bootswatch.git to /tmp/pip-5TesnT-build
Installing collected packages: mkdocs-bootswatch
  Running setup.py install for mkdocs-bootswatch ... done
Successfully installed mkdocs-bootswatch-0.4.0
WARNING -  The theme 'flatly' does not appear to have a configuration file. Please upgrade to a current version of the theme. 
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/travis/build/ThingPulse/docs/site 
```

It's odd because `mkdocs_theme.yml` _does_ [exist in `_base`](https://github.com/mkdocs/mkdocs-bootswatch/blob/master/src/_base/mkdocs_theme.yml).

**Comment by bulletmark** [comment] 2018-02-08 00:49
@isaccavalcante, your comment fixed this same issue for me also, thanks.

**Comment by waylan** [comment] 2018-02-13 20:19
Closing this as a duplicate of #36.

**Closed by waylan** 2018-02-13 20:19 UTC
